console.log('Hello Winc Academy');
let name = 'Jitske';
console.log(name);
console.log(4+4);
console.log('4'+'4');
console.log(4-4);
console.log(4*4);
console.log(4/4);
console.log(4%4);
let age = 32;
console.log(typeof age);
age = '32';
console.log(typeof age);
